<?php
enum Prefecture: int {
    case HOKKAIDO    = 1;
    case AOMORI      = 2;
    case IWATE       = 3;
    case MIYAGI      = 4;
    case AKITA       = 5;
    case YAMAGATA    = 6;
    case FUKUSHIMA   = 7;
    case IBARAKI     = 8;
    case TOCHIGI     = 9;
    case GUNMA       = 10;
    case SAITAMA     = 11;
    case CHIBA       = 12;
    case TOKYO       = 13;
    case KANAGAWA    = 14;
    case NIIGATA     = 15;
    case TOYAMA      = 16;
    case ISHIKAWA    = 17;
    case FUKUI       = 18;
    case YAMANASHI   = 19;
    case NAGANO      = 20;
    case GIFU        = 21;
    case SHIZUOKA    = 22;
    case AICHI       = 23;
    case MIE         = 24;
    case SHIGA       = 25;
    case KYOTO       = 26;
    case OSAKA       = 27;
    case HYOGO       = 28;
    case NARA        = 29;
    case WAKAYAMA    = 30;
    case TOTTORI     = 31;
    case SHIMANE     = 32;
    case OKAYAMA     = 33;
    case HIROSHIMA   = 34;
    case YAMAGUCHI   = 35;
    case TOKUSHIMA   = 36;
    case KAGAWA      = 37;
    case EHIME       = 38;
    case KOCHI       = 39;
    case FUKUOKA     = 40;
    case SAGA        = 41;
    case NAGASAKI    = 42;
    case KUMAMOTO    = 43;
    case OITA        = 44;
    case MIYAZAKI    = 45;
    case KAGOSHIMA   = 46;
    case OKINAWA     = 47;

    public function label(): string {
            return match($this) {
                self::HOKKAIDO    => "北海道",
                self::AOMORI      => "青森",
                self::IWATE       => "岩手",
                self::MIYAGI      => "宮城",
                self::AKITA       => "秋田",
                self::YAMAGATA    => "山形",
                self::FUKUSHIMA   => "福島",
                self::IBARAKI     => "茨城",
                self::TOCHIGI     => "栃木",
                self::GUNMA       => "群馬",
                self::SAITAMA     => "埼玉",
                self::CHIBA       => "千葉",
                self::TOKYO       => "東京",
                self::KANAGAWA    => "神奈川",
                self::NIIGATA     => "新潟",
                self::TOYAMA      => "富山",
                self::ISHIKAWA    => "石川",
                self::FUKUI       => "福井",
                self::YAMANASHI   => "山梨",
                self::NAGANO      => "長野",
                self::GIFU        => "岐阜",
                self::SHIZUOKA    => "静岡",
                self::AICHI       => "愛知",
                self::MIE         => "三重",
                self::SHIGA       => "滋賀",
                self::KYOTO       => "京都",
                self::OSAKA       => "大阪",
                self::HYOGO       => "兵庫",
                self::NARA        => "奈良",
                self::WAKAYAMA    => "和歌山",
                self::TOTTORI     => "鳥取",
                self::SHIMANE     => "島根",
                self::OKAYAMA     => "岡山",
                self::HIROSHIMA   => "広島",
                self::YAMAGUCHI   => "山口",
                self::TOKUSHIMA   => "徳島",
                self::KAGAWA      => "香川",
                self::EHIME       => "愛媛",
                self::KOCHI       => "高知",
                self::FUKUOKA     => "福岡",
                self::SAGA        => "佐賀",
                self::NAGASAKI    => "長崎",
                self::KUMAMOTO    => "熊本",
                self::OITA        => "大分",
                self::MIYAZAKI    => "宮崎",
                self::KAGOSHIMA   => "鹿児島",
                self::OKINAWA     => "沖縄",
            };
        }
    }
